photography/urls.py
from unicodedata import name
from django.urls import path
from .views import AboutPageView, ContactPageView, HomePageView, PhotoListView, PhotoDetailView

app_name = 'photography'

urlpatterns = [
    # Home Page.
    path('', HomePageView.as_view(), name='home'),
    # Collection of images page.
    path('photo/collection/', PhotoListView.as_view(), name='list'),
    # Detail view of each photo.
    path('photo/detail/', PhotoDetailView.as_view(), name= 'detail'),
    # About me page.
    path('About/', AboutPageView.as_view(), name='about'),
    # Contact page.
    path('Contact/', ContactPageView.as_view(), name='contact'),
]

project_structure/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # Main app urls.
    path('', include('photography.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photography/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

class Photo(models.Model):
    title = models.CharField(max_length=45)
    description = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='photos/')
    submitter = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.title

photography/views.py
from typing import List
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.core.exceptions import PermissionDenied
from django.views.generic import ListView, DetailView, TemplateView
from django.urls import reverse_lazy
from .models import Photo

# Create your views here.
class HomePageView(TemplateView):
    template_name = 'home.html'

class AboutPageView(TemplateView):
    template_name = 'about.html'

class ContactPageView(TemplateView):
    template_name = 'contact.html'

class PhotoListView(ListView):
    model = Photo
    template_name = 'portfollio.html'
    context_object_name = 'photos'

class PhotoDetailView(DetailView):
    model = Photo
    template_name = 'photography/detail.html'
    context_object_name = 'photo'

templates/about.html
{% extends "base.html" %}

{% block title %}About Me{% endblock title %}

{% block content %}

    <section class="picture-body2">   
    </section>

    <section class="about-body">
    <section class="about-title">
        <h1>About Mr.Basave</h1>
    </section>
    <section class="about-description">
        <p>
            This website is to showcase the wonderful photography skills of my good friend Jonathan. He is a great man whom I grew up with in the small city of El Paso. Jonathan Basave has always had a passion for capturing moments that allow friends and viewers to feel certain emotions. I have been fortunate enough to enjoy his art and hope you all enjoy as well.
        </p>
    </section>

    </section>

{% endblock content %}

templates/base.html
{% load django_bootstrap5%}
{% load static %}

<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Besley&display=swap" rel="stylesheet">

    <link rel="stylesheet"  type="text/css" href="{% static 'photography/css/style.css' %}">
    <script src="https://kit.fontawesome.com/9f61a45b3f.js" crossorigin="anonymous"></script>

    {% block title %}
    <title>HomePage</title>
    {% endblock title %}

    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>

    <header> 
         <a class="header-brand" href="{% url 'photography:home' %}"><i class="fas fa-camera-retro"> Basave Photography</i></a>

        <nav>
            <div class="nav-right">
                <ul>
                    <li>
                        <a href="{% url 'photography:list' %}"><i class="fas fa-folder-open"> Portfollio</i></a>
                    </li>
                    <li>
                        <a href="{% url 'photography:about' %}"><i class="fas fa-user-circle"> About Me</i></a>
                    </li>
                    <li class="last-link">
                        <a href="{% url 'photography:contact' %}"><i class="fas fa-mobile"> Contact</i></a>
                    </li>
                </ul>
            </div>
        </nav>             
    </header>

    <main>
        {% block content %}{% endblock content %} 
    </main>

</body>
</html>

templates/contact.html
{% extends "base.html" %}

{% block title %}Contact{% endblock title %}

{% block content %}

    <section class='text-body'>
        <div class='contact-body'>
             <h6>If You'd like to get in touch, contact me at</h6>
             <h5>BasavePhotography@gmail.com</h1>
        </div>
     </section>
    <section class='picture-body'>   
    </section>
    
{% endblock content %}

templates/home.html
{% extends "base.html" %}

{% block title %}HomePage{% endblock title %}

{% block content %}
    <section class="home-banner">
        <div class="vertical-center">
            <h5>My name is Jonathan and I love</h3>
            <h1>Photography</h1>
        </div>
    </section>
{% endblock content %}

templates/portfollio.html
{% extends "base.html" %}

{% block title %}Portfollio{% endblock title %}

{% block content %}
    <section class="portfollio-title">
        <h1>Portfollio</h1>
    </section>
    <div class="row">
        {% for photo in photos %}
        <div class="col-lg-3 col-md-4 col-xs-6">
          
            <img  id="individual" src="{{photo.image.url}}" class="img-fluid rounded" alt="{{photo.title}}" />
        
        </div>
        {% endfor %}
      </div>
{% endblock content %}k 